CREATE TABLE Person (
                        person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name VARCHAR(250) UNIQUE,
                        year_of_birth varchar(60) NOT NULL
);

INSERT INTO Person (full_name, year_of_birth)
VALUES ('Иванов Иван Иванович', '12.12.2002'),
       ('Петров Пётр Петрович', '13.12.2003'),
       ('Алексеев Алексей Алексеевич', '14.12.2004'),
       ('Познер Владимир Владимирович', '15.12.2005'),
       ('Фёдоров Мирон Янович', '16.12.2006');

CREATE TABLE Book (
                      book_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      person_id INT REFERENCES Person(person_id) ON DELETE SET NULL,
                      title VARCHAR(100) NOT NULL,
                      author VARCHAR(250) NOT NULL,
                      realise_date varchar(50) NOT NULL ,
                      receiving_date TIMESTAMP
);

INSERT INTO Book (title, author, realise_date)
VALUES ('Над пропастью во ржи', 'Джером Сэлинджер', '12.12.2002'),
       ('День опричника', 'Владимир Сорокин', '12.12.2003'),
       ('Тайные виды на гору Фудзи', 'Владимир Пелевин', '12.12.2004'),
       ('Философия Java', 'Брюс Эккель', '12.12.2005'),
       ('Игра в бисер', 'Герман Гессе', '12.12.2006'),
       ('Бытие и время', 'Мартин Хайдеггер', '12.12.2007'),
       ('Психопатология обыденной жизни', 'Зигмунд Фрейд', '12.12.2008'),
-- вторую книгу по психологии я добавила для тестирования поиска
       ('Психология влияния', 'Роберт Чалдини', '12.12.2009');